export const selectIsConnectedToRopsten = state => state.sContract.connectedToRopsten
export const selectSurveyContract = state => state.sContract.surveyContract
export const selectIsLoading = state => state.sContract.loading
export const selectIsLoadingBalance = state => state.sContract.loadingBalance
export const selectBalance = state => state.sContract.balance
export const selectSuccess = state => state.sContract.success
export const selectSuccessMsg = state => state.sContract.successMsg
export const selectError = state => state.sContract.error
export const selectErrorMsg = state => state.sContract.errorMsg